package org.tawhid.readout.core.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val shimmer = Color(0xFFC3C3C3)
val shimmerColors = listOf(
    shimmer.copy(alpha = 0.3f),
    shimmer.copy(alpha = 0.5f),
    shimmer.copy(alpha = 1.0f),
    shimmer.copy(alpha = 0.5f),
    shimmer.copy(alpha = 0.3f),
)

val SandYellow = Color(0xFFFFBD64)

val primaryLight = Color(0xFF0078e6)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF0078e6)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF1E88E5)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF0077CE)
val onSecondaryContainerLight = Color(0xFFFFFFFF)
val tertiaryLight = Color(0xFF9a21c0)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFAB36D0)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFfe3f60)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFDE284A)
val onErrorContainerLight = Color(0xFFFFFFFF)
val backgroundLight = Color(0xFFFAF8FF)
val onBackgroundLight = Color(0xFF191B25)
val surfaceLight = Color(0xFFFAF8FF)
val onSurfaceLight = Color(0xFF191B25)
val surfaceVariantLight = Color(0xFFDFE1F6)
val onSurfaceVariantLight = Color(0xFF434656)
val outlineLight = Color(0xFF737688)
val outlineVariantLight = Color(0xFFC3C5D9)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2E303A)
val inverseOnSurfaceLight = Color(0xFFF0F0FD)
val inversePrimaryLight = Color(0xFFB6C4FF)
val surfaceDimLight = Color(0xFFD9D9E6)
val surfaceBrightLight = Color(0xFFFAF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF3F2FF)
val surfaceContainerLight = Color(0xFFEDEDFA)
val surfaceContainerHighLight = Color(0xFFE7E7F5)
val surfaceContainerHighestLight = Color(0xFFE1E1EF)


val primaryDark = Color(0xFFB6C4FF)
val onPrimaryDark = Color(0xFF00277F)
val primaryContainerDark = Color(0xFF004FEB)
val onPrimaryContainerDark = Color(0xFFFFFFFF)
val secondaryDark = Color(0xFFA2C9FF)
val onSecondaryDark = Color(0xFF00315B)
val secondaryContainerDark = Color(0xFF0077CE)
val onSecondaryContainerDark = Color(0xFFFFFFFF)
val tertiaryDark = Color(0xFFF0B0FF)
val onTertiaryDark = Color(0xFF54006D)
val tertiaryContainerDark = Color(0xFF9010B7)
val onTertiaryContainerDark = Color(0xFFFFFEFF)
val errorDark = Color(0xFFFFB3B5)
val onErrorDark = Color(0xFF680019)
val errorContainerDark = Color(0xFFDE284A)
val onErrorContainerDark = Color(0xFFFFFFFF)
val backgroundDark = Color(0xFF11131C)
val onBackgroundDark = Color(0xFFE1E1EF)
val surfaceDark = Color(0xFF11131C)
val onSurfaceDark = Color(0xFFE1E1EF)
val surfaceVariantDark = Color(0xFF434656)
val onSurfaceVariantDark = Color(0xFFC3C5D9)
val outlineDark = Color(0xFF8D90A2)
val outlineVariantDark = Color(0xFF434656)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE1E1EF)
val inverseOnSurfaceDark = Color(0xFF2E303A)
val inversePrimaryDark = Color(0xFF004EE7)
val surfaceDimDark = Color(0xFF11131C)
val surfaceBrightDark = Color(0xFF373943)
val surfaceContainerLowestDark = Color(0xFF0C0E17)
val surfaceContainerLowDark = Color(0xFF191B25)
val surfaceContainerDark = Color(0xFF1D1F29)
val surfaceContainerHighDark = Color(0xFF272933)
val surfaceContainerHighestDark = Color(0xFF32343E)

val LightColorScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

val DarkColorScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)